version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - 3000:3000

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
    ports:
      - 5432:5432
